CREATE TABLE facilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    phone TEXT,
    facility_id TEXT,
    permit_holder TEXT,
    program_identifier TEXT,
    facility_type TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE inspection_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    facility_id INTEGER NOT NULL,
    permit_id TEXT,
    inspection_date TEXT,
    inspection_type TEXT,
    inspector_name TEXT,
    inspector_phone TEXT,
    report_recipient TEXT,
    total_violations INTEGER DEFAULT 0,
    major_violations INTEGER DEFAULT 0,
    pdf_filename TEXT,
    pdf_path TEXT,
    report_notes TEXT,
    co_inspector TEXT,
    reinspection_required BOOLEAN DEFAULT FALSE,
    closure_suspension_required BOOLEAN DEFAULT FALSE,
    barcode_data TEXT,
    pool_capacity_gallons INTEGER,
    pool_flow_rate_gpm INTEGER,
    water_chemistry_details TEXT,
    closure_status TEXT DEFAULT 'operational',
    closure_reason TEXT,
    inspection_id TEXT UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (facility_id) REFERENCES facilities(id)
);
CREATE TABLE violations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_id INTEGER NOT NULL,
    facility_id INTEGER NOT NULL,
    violation_code TEXT,
    violation_title TEXT,
    observations TEXT,
    corrective_action TEXT,
    code_description TEXT,
    is_major_violation BOOLEAN DEFAULT FALSE,
    severity_level INTEGER,
    correction_deadline_days INTEGER,
    shorthand_summary TEXT,
    FOREIGN KEY (report_id) REFERENCES inspection_reports(id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id)
);
CREATE TABLE equipment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    report_id INTEGER NOT NULL,
    facility_id INTEGER NOT NULL,
    pool_capacity_gallons INTEGER,
    flow_rate_gpm INTEGER,
    filter_pump_1_make TEXT, filter_pump_1_model TEXT, filter_pump_1_hp REAL,
    filter_pump_2_make TEXT, filter_pump_2_model TEXT, filter_pump_2_hp REAL,
    filter_pump_3_make TEXT, filter_pump_3_model TEXT, filter_pump_3_hp REAL,
    jet_pump_1_make TEXT, jet_pump_1_model TEXT, jet_pump_1_hp REAL,
    jet_pump_2_make TEXT, jet_pump_2_model TEXT, jet_pump_2_hp REAL,
    filter_1_type TEXT, filter_1_make TEXT, filter_1_model TEXT, filter_1_capacity_gpm INTEGER,
    filter_2_type TEXT, filter_2_make TEXT, filter_2_model TEXT, filter_2_capacity_gpm INTEGER,
    sanitizer_1_type TEXT, sanitizer_1_details TEXT,
    sanitizer_2_type TEXT, sanitizer_2_details TEXT,
    main_drain_type TEXT, main_drain_model TEXT, main_drain_install_date TEXT,
    equalizer_model TEXT, equalizer_install_date TEXT,
    equipment_matches_emd BOOLEAN DEFAULT TRUE,
    filter_notes TEXT, pump_notes TEXT, jet_pump_notes TEXT,
    sanitizer_notes TEXT, main_drain_notes TEXT, equalizer_notes TEXT, equipment_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (report_id) REFERENCES inspection_reports(id),
    FOREIGN KEY (facility_id) REFERENCES facilities(id)
);
CREATE TABLE violation_summary_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fingerprint TEXT NOT NULL UNIQUE,
    original_title TEXT NOT NULL,
    original_observations TEXT NOT NULL,
    shorthand_summary TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
